In [3]:
import nba_stats_historical_datapull as hist
import pandas as pd
import numpy as np
import nba_api
from nba_api.stats.static import players
from nba_api.stats.static import teams
from nba_api.stats.endpoints import commonteamroster as rosters
from nba_api.stats.endpoints import playergamelog
from nba_api.stats.endpoints import playbyplayv2 as pbp
from nba_api.stats.endpoints import commonallplayers
from nba_api.stats.endpoints import teamgamelog
from nba_api.stats.endpoints import winprobabilitypbp as winprob
from nba_api.stats.endpoints import BoxScoreAdvancedV3 as box
import time
from datetime import datetime

In [ ]:
# CommonAllPlayers - TO_YEAR is the best measure. means they have at some point played in a game this year.
# players.get_active_players - this is players currently on an active roster. 
    # can show up on this list and not the above (based on this year TO YEAR) if on roster but have not appeared in a game yet

In [41]:
current_rosters_df = rosters.CommonTeamRoster(1610612749).get_data_frames()[0]
# current_rosters_df = pd.DataFrame(current_rosters_obj.get_data_frames()[0])
# current_rosters_df

In [117]:
# returns full list of all players who played in the nba
# ROSTERSTATUS = 1 seems to be is_active
all_players = commonallplayers.CommonAllPlayers().get_data_frames()[0]
all_players['TO_YEAR'] = all_players['TO_YEAR'].apply(lambda x: int(x))
historical_full = all_players[all_players['TO_YEAR']>= 2010]
hist_players = historical_full.copy()

,PERSON_ID,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FIRST_LAST,ROSTERSTATUS,FROM_YEAR,TO_YEAR,PLAYERCODE,PLAYER_SLUG,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CODE,TEAM_SLUG,GAMES_PLAYED_FLAG,OTHERLEAGUE_EXPERIENCE_CH
9,203518,"Abrines, Alex",Alex Abrines,0,2016,2018,alex_abrines,alex_abrines,0,,,,,None,Y,00
10,1630173,"Achiuwa, Precious",Precious Achiuwa,1,2020,2023,precious_achiuwa,precious_achiuwa,1610612752,New York,Knicks,NYK,knicks,knicks,Y,00

In [118]:
hist_players = hist_players[['PERSON_ID', 'DISPLAY_FIRST_LAST', 'TO_YEAR']]
hist_players.loc[:, 'total_seasons'] = hist_players['TO_YEAR'] - 2009

In [154]:
hist_players.loc[:,'seasons_played'] = hist_players['total_seasons'].apply(lambda x: [year for season in range(2010, 2010 + x) for year in [season]])

id_season_df = hist_players[['PERSON_ID','seasons_played']]
test_df = id_season_df[:2]
test_df
len(id_season_df)

1721

In [149]:
id_season_pair_list = []
for index, row in id_season_df.iterrows():
    player_id = row['PERSON_ID']
    seasons_played = row['seasons_played']
    player_entry = {'PERSON_ID': player_id, 'seasons_played': seasons_played}
    id_season_pair_list.append(player_entry)

In [150]:
len(id_season_pair_list)
# id_season_pair_list[0]
# id_season_pair_list[0]['seasons_played']

1721

In [151]:
id_season_pairs = []

for pair in id_season_pair_list:
    player_id = pair['PERSON_ID']
    player_pairs = [{'player_id': player_id, 'season_year': season} for season in pair['seasons_played']]
    id_season_pairs.extend(player_pairs)

all_ids_all_years = pd.DataFrame(id_season_pairs)

In [188]:
test_df = all_ids_all_years[all_ids_all_years['season_year']>=2016]
test = test_df[:2]

In [218]:




games_2022 = all_ids_all_years[all_ids_all_years['season_year']==2022]

In [225]:
gamelog_df_list = []
start_time = time.time()
formatted_start = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(start_time))
for index, row in games_2022.iterrows():
    player_id = row['player_id'] 
    season = row['season_year']
    player_gamelog = playergamelog.PlayerGameLog(player_id, season)
    player_gamelog_df = player_gamelog.get_data_frames()[0]
    print(player_id, season)
    gamelog_df_list.append(player_gamelog_df)
    time.sleep(.1)

player_gamelogs_df = pd.concat(gamelog_df_list, ignore_index=True)
player_gamelogs_df.to_csv(f'player_gamelogs_{str(season)}.csv', index=False)

end_time = time.time()
duration = round((end_time - start_time)/60, 2)
formatted_end = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(end_time))
print(formatted_start)
print(formatted_end)
print(str(duration) + ' minutes')
print(f'{str(season)} is complete. {len(player_gamelogs_df)} total player gamelogs')

1630173 2022
203500 2022
1628389 2022
1630534 2022
1630583 2022
1629638 2022
1628960 2022
1628386 2022
1630631 2022
203937 2022
203507 2022
203648 2022
1630175 2022
1628384 2022
1627853 2022
201571 2022
1630166 2022
1629028 2022
1628962 2022
1630641 2022
1628963 2022
1641735 2022
1631116 2022
1630163 2022
1628366 2022
1628964 2022
1631094 2022
1630217 2022
1630625 2022
1631230 2022
203084 2022
1630567 2022
1629628 2022
203115 2022
1629646 2022
1641734 2022
1628966 2022
201587 2022
1629647 2022
203078 2022
1627736 2022
1630699 2022
1631262 2022
202722 2022
201976 2022
1630180 2022
203920 2022
1629048 2022
1641931 2022
202687 2022
1641710 2022
1641778 2022
1631205 2022
203992 2022
202711 2022
1629626 2022
1629716 2022
1630195 2022
1626164 2022
1630527 2022
1628449 2022
1630547 2022
1631123 2022
1628396 2022
1631103 2022
1629714 2022
1631128 2022
1628969 2022
1628970 2022
1629052 2022
1631167 2022
1627763 2022
1629717 2022
1628415 2022
1628971 2022
1627759 2022
1631112 2022
1641738 2022
1629650 2022
1628425 2022
1630535 2022
1629718 2022
1628972 2022
1628973 2022
1628418 2022
1641723 2022
203493 2022
202692 2022
1629126 2022
1630215 2022
202710 2022
1631219 2022
1631288 2022
203484 2022
1641739 2022
1630267 2022
1628427 2022
203991 2022
1630176 2022
1628975 2022
1628976 2022
203487 2022
1630618 2022
1627936 2022
1630658 2022
1626161 2022
1630608 2022
1630577 2022
1630551 2022
1631113 2022
1631108 2022
1630528 2022
1631321 2022
1641740 2022
1629634 2022
203903 2022
1629651 2022
1641730 2022
1629599 2022
1628381 2022
1628380 2022
1628435 2022
201144 2022
1626192 2022
1641645 2022
1641731 2022
1641741 2022
203496 2022
1628470 2022
203109 2022
1630622 2022
1629633 2022
1630595 2022
203552 2022
201939 2022
1630700 2022
203076 2022
1631098 2022
1629056 2022
1631120 2022
1630620 2022
201942 2022
203473 2022
203521 2022
1641926 2022
1628978 2022
1631217 2022
1629603 2022
1628977 2022
1641711 2022
203476 2022
1631172 2022
203915 2022
1629029 2022
1628416 2022
1629652 2022
1630245 2022
1629653 2022
1630288 2022
1628408 2022
201609 2022
1630929 2022
203083 2022
1630537 2022
1630561 2022
1627739 2022
201142 2022
1631105 2022
1631106 2022
1630162 2022
1630556 2022
1631165 2022
203954 2022
1629234 2022
1641787 2022
203957 2022
1628981 2022
1627827 2022
1641745 2022
1630201 2022
1631323 2022
1627854 2022
1630259 2022
1630235 2022
1630701 2022
203095 2022
1628368 2022
1631241 2022
1641788 2022
1628365 2022
1641847 2022
1629117 2022
1629655 2022
201568 2022
1641945 2022
1629636 2022
1630586 2022
1630568 2022
1629232 2022
200752 2022
1641718 2022
202331 2022
201959 2022
1630581 2022
1628385 2022
1628983 2022
1630264 2022
1631221 2022
1631367 2022
203497 2022
1630692 2022
203932 2022
201569 2022
1628984 2022
203924 2022
1630564 2022
1631260 2022
201980 2022
203110 2022
203210 2022
1630224 2022
1629750 2022
201145 2022
1630182 2022
1631100 2022
201933 2022
1629656 2022
1631338 2022
1631243 2022
1629060 2022
1630204 2022
1630169 2022
1631160 2022
1630181 2022
203501 2022
201935 2022
1630702 2022
1631199 2022
1626149 2022
203914 2022
203925 2022
1630284 2022
202699 2022
1627885 2022
1628404 2022
1628392 2022
2617 2022
1630573 2022
1641722 2022
1629637 2022
1630165 2022
202330 2022
1630703 2022
1641707 2022
1627823 2022
1626195 2022
1629639 2022
1627741 2022
1629312 2022
201588 2022
1630792 2022
1630207 2022
1641793 2022
1628988 2022
201950 2022
203200 2022
1626158 2022
1631096 2022
1641720 2022
201143 2022
1629659 2022
1627863 2022
1631216 2022
1641724 2022
1631309 2022
1628989 2022
1630643 2022
1629631 2022
1630562 2022
1630538 2022
201586 2022
2738 2022
204060 2022
1627742 2022
202681 2022
1628371 2022
1631093 2022
1628402 2022
1641713 2022
1630543 2022
1628382 2022
1631245 2022
202704 2022
1641748 2022
1628991 2022
1631218 2022
2544 2022
1631170 2022
1630610 2022
1629610 2022
1641998 2022
1629660 2022
1630198 2022
1628993 2022
1629661 2022
1630552 2022
201949 2022
1629640 2022
1630553 2022
1641749 2022
1626169 2022
203999 2022
1630637 2022
1641732 2022
1627745 2022
1630529 2022
1630539 2022
1630222 2022
1630200 2022
1626145 2022
1627884 2022
201599 2022
202709 2022
1631107 2022
1630548 2022
1629662 2022
1626163 2022
1631211 2022
1628379 2022
1631117 2022
1630296 2022
1629663 2022
1630557 2022
1628467 2022
1630233 2022
1628995 2022
1631132 2022
1629723 2022
1627788 2022
1628436 2022
1630249 2022
1630228 2022
1628398 2022
1631222 2022
203897 2022
1630237 2022
1629111 2022
1629641 2022
1630639 2022
1627747 2022
1627814 2022
1630240 2022
203458 2022
202695 2022
203086 2022
1631171 2022
1641721 2022
1630184 2022
1630604 2022
203081 2022
1629642 2022
1641726 2022
1630587 2022
1641753 2022
1631254 2022
1626172 2022
201572 2022
201577 2022
201567 2022
200768 2022
1641754 2022
1626168 2022
1630177 2022
1630572 2022
1629611 2022
1630544 2022
1626246 2022
1628374 2022
1630230 2022
1628997 2022
1628998 2022
1641798 2022
1630231 2022
1631213 2022
1629726 2022
1631097 2022
202083 2022
1630178 2022
1630219 2022
1630540 2022
1630644 2022
203468 2022
204456 2022
1630183 2022
1629667 2022
203926 2022
201580 2022
1631121 2022
203585 2022
1629162 2022
1629001 2022
1641877 2022
1630241 2022
1629002 2022
203995 2022
203114 2022
1641706 2022
1641757 2022
1631159 2022
201988 2022
1629003 2022
1631303 2022
1631169 2022
1630558 2022
1628378 2022
1630596 2022
1630600 2022
1631320 2022
1628370 2022
1630541 2022
1629875 2022
1631386 2022
1631111 2022
1629630 2022
202693 2022
1628420 2022
202694 2022
1630530 2022
1627749 2022
1627750 2022
1631099 2022
1631200 2022
203488 2022
1629004 2022
1631250 2022
1626204 2022
1629614 2022
1630174 2022
203526 2022
1627777 2022
1630227 2022
1630192 2022
203457 2022
1629669 2022
1641806 2022
1628373 2022
1629134 2022
203994 2022
1629670 2022
1626220 2022
1629643 2022
1629006 2022
1630168 2022
1630171 2022
1629644 2022
203506 2022
203482 2022
1630647 2022
1626224 2022
1626162 2022
101108 2022
1626166 2022
1627780 2022
1641809 2022
1630196 2022
1641763 2022
1629618 2022
1629033 2022
1630590 2022
203486 2022
1641764 2022
1627751 2022
1630197 2022
1629673 2022
1629007 2022
1641854 2022
1629645 2022
1629008 2022
203490 2022
1626171 2022
204001 2022
1630695 2022
203939 2022
1626181 2022
1630554 2022
1630563 2022
1627752 2022
1630202 2022
1641765 2022
1630243 2022
1629674 2022
1630193 2022
1631311 2022
1630186 2022
203944 2022
1641871 2022
1630559 2022
1629629 2022
1628432 2022
1630194 2022
1629675 2022
1631197 2022
1630208 2022
1626196 2022
203085 2022
1629130 2022
1629010 2022
1629011 2022
1631115 2022
1630526 2022
1629676 2022
1631223 2022
1631157 2022
201565 2022
203082 2022
1626179 2022
201937 2022
1641712 2022
1626156 2022
1630346 2022
1627734 2022
1629677 2022
1631257 2022
1641766 2022
1630611 2022
203967 2022
1630846 2022
1631204 2022
1630648 2022
1629678 2022
203471 2022
1630206 2022
1631220 2022
1630578 2022
1641729 2022
1629012 2022
1629013 2022
1630549 2022
1631101 2022
1641767 2022
1627783 2022
1629735 2022
1627732 2022
1628424 2022
1630250 2022
1629014 2022
1630579 2022
1631376 2022
1641771 2022
1630606 2022
203935 2022
1630696 2022
202397 2022
1630188 2022
1631173 2022
1628372 2022
1631095 2022
1641733 2022
1630270 2022
1631110 2022
1630311 2022
1630531 2022
1630205 2022
1630191 2022
1631124 2022
1629622 2022
1630591 2022
1628410 2022
1631306 2022
1630256 2022
1628369 2022
1630678 2022
202066 2022
1631207 2022
1628464 2022
1630560 2022
1641708 2022
1641709 2022
202691 2022
202684 2022
1630550 2022
1629680 2022
1630214 2022
1630225 2022
1631210 2022
1630167 2022
1629308 2022
1626157 2022
1629018 2022
1631131 2022
200782 2022
1626167 2022
1641816 2022
1630649 2022
202685 2022
1627832 2022
1629020 2022
1630170 2022
1628426 2022
1629216 2022
203943 2022
202696 2022
1629731 2022
1630532 2022
1629021 2022
1630688 2022
1631133 2022
1641716 2022
202689 2022
1629022 2022
202322 2022
1641717 2022
1641775 2022
203933 2022
1629023 2022
1630613 2022
1631102 2022
1629139 2022
1630322 2022
1630570 2022
1631212 2022
1641705 2022
1631104 2022
201566 2022
1629632 2022
1628401 2022
1631298 2022
1641727 2022
1641715 2022
1630580 2022
1630598 2022
203952 2022
1629623 2022
1631214 2022
1630314 2022
1631495 2022
1629684 2022
1631114 2022
1631119 2022
1629026 2022
1631109 2022
1631466 2022
1630172 2022
1630533 2022
1629057 2022
1631246 2022
1629627 2022
1630592 2022
1629685 2022
1626159 2022
1630164 2022
1631209 2022
1626174 2022
1626153 2022
1630593 2022
1628221 2022
201152 2022
1629027 2022
1630209 2022
203469 2022
1627826 2022
2024-03-13 20:32:31
2024-03-13 20:37:08
4.62 minutes
2022 is complete. 25895 total player gamelogs

/var/folders/b6/pcl5v3g16_x0bgrtf8b8y8n40000gn/T/ipykernel_54650/2821767948.py:14: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  player_gamelogs_df = pd.concat(gamelog_df_list, ignore_index=True)